# Site settings.
# This is where you can put site-wide settings.
# Any values placed here are globally accessible
# from any template context via the `site` key.
site:
  title: Harry Wolff
  author: Harry Wolff
  email: hello@hswolff.com
  description: Personal site of Harry Wolff (hswolff).
  url: "http://hswolff.com/"
  gravatar_url: 'http://www.gravatar.com/avatar/f863e9eb811851834773398e72614dc1?d=404'
  disqus_url: hswolff.com

# Where things are.
# If you have a unique layout for your site and want to
# change where Reptar looks for certain files you can change
# them here. All files are relative to where the `_config.yml`
# is found.
path:
  source:      ./
  destination: ./_site
  plugins:     ./_plugins
  themes:      ./_themes

# Individual File configuration.
file:
  defaults:
    -
      scope:
         path: ./
      values:
        template: page
    -
      scope:
         path: ./_posts
      values:
        template: post
        permalink: /blog/:slug/
  filters:
    metadata:
      draft: true
    future_date:
      key: date

# This is where you configure your collections of content.
# For more details refer to the Collections documentation.
collections:
  post:
    path: ./_posts
    template: index
    page_size: 6
    sort:
      key: date
      order: descending
    permalink:
      index: /
      page:  /blog/page/:page/
  tag:
    metadata: tags
    template: tag
    page_size: 6
    sort:
      key: date
      order: descending
    permalink:
      index: /blog/tag/:metadata/
      page:  /blog/tag/:metadata/:page/

# Current theme.
# What theme your Reptar site should use when building your site.
theme: 'default'

# If we should remove the compile destination folder before writing.
clean_destination: false

# Only build files that have changed.
# This is a performance improvement to the time it takes to build your site.
incremental: true

# Slug options.
# Options passed to node-slug
slug:
  lower: true

# Markdown.
# This lets you customize how markdown is handled.
markdown:
  # What file extensions we should recognize as a markdown file.
  extensions:
    - markdown
    - mkdown
    - mkdn
    - mkd
    - md
  # Options given directly when creating our markdown parser.
  # Documentation here:
  # https://github.com/markdown-it/markdown-it#init-with-presets-and-options
  options:
    preset:       'commonmark'
    highlight:    true

# Serving.
# When running `yarn serve` what settings should be used.
server:
  port:    8080
  host:    127.0.0.1
  baseurl: "" # does not include hostname

# Where files created via `yarn new` should be placed.
new_file_permalink: '/_posts/:date|YYYY/:date|YYYY-:date|MM-:date|D-:title.md'

# What plugins you want enabled and what configuration settings they should have.
plugins:
  html-minifier:
    enabled: true
  excerpt:
    enabled: true
